/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Icon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ImageCta = {
  _type: 'imageCta'
  headline: string
  ctaText?: string
  ctaUrl?: string
  backgroundImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  overlayOpacity?: number
}

export type TestimonialsCarousel = {
  _type: 'testimonialsCarousel'
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  headline?: string
  testimonials?: Array<{
    quote: string
    name: string
    descriptor?: string
    _key: string
  }>
}

export type StatsBand = {
  _type: 'statsBand'
  showLogo?: boolean
  stats?: Array<{
    value: string
    label: string
    icon?: string
    _key: string
  }>
}

export type ComparisonTable = {
  _type: 'comparisonTable'
  headline: string
  subheadline?: string
  competitors?: Array<string>
  highlightColumnName?: string
  checkIcon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  xIcon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  rows?: Array<{
    feature: string
    values?: Array<boolean>
    _key: string
  }>
}

export type FeatureBlock = {
  _type: 'featureBlock'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imagePosition?: 'left' | 'right'
  headline: string
  ctaText?: string
  ctaUrl?: string
  ctaVariant?: 'primary' | 'secondary' | 'outline'
  label?: string
  listItems?: Array<{
    icon?: string
    text: string
    _key: string
  }>
}

export type StatsIconBar = {
  _type: 'statsIconBar'
  items?: Array<{
    icon?: Icon
    iconFallback?: string
    label: string
    _key: string
  }>
}

export type HeroSection = {
  _type: 'heroSection'
  ratingCount?: string
  headline: string
  headlineEmphasis?: string
  subtext?: string
  ctaText?: string
  ctaUrl?: string
  microCopy?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type AnnouncementBar = {
  _type: 'announcementBar'
  text?: string
  linkText?: string
  linkUrl?: string
  isVisible?: boolean
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type FooterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footer'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  phone?: string
  email?: string
  address?: string
  announcementBar?: AnnouncementBar
  navigation?: Array<{
    label: string
    url: string
    _key: string
  }>
  footer?: FooterReference
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  tagline?: string
  columns?: Array<{
    title: string
    links?: Array<{
      label: string
      url: string
      _key: string
    }>
    _key: string
  }>
  address?: string
  phone?: string
  email?: string
  copyrightText?: string
  parentCompany?: string
  parentCompanyUrl?: string
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading?: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroSection)
    | ({
        _key: string
      } & StatsIconBar)
    | ({
        _key: string
      } & FeatureBlock)
    | ({
        _key: string
      } & ComparisonTable)
    | ({
        _key: string
      } & StatsBand)
    | ({
        _key: string
      } & TestimonialsCarousel)
    | ({
        _key: string
      } & ImageCta)
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Icon
  | ImageCta
  | TestimonialsCarousel
  | StatsBand
  | ComparisonTable
  | FeatureBlock
  | StatsIconBar
  | HeroSection
  | AnnouncementBar
  | PageReference
  | PostReference
  | Link
  | BlockContentTextOnly
  | BlockContent
  | Button
  | FooterReference
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Footer
  | PersonReference
  | Post
  | Person
  | Slug
  | Page
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{  ...,  footer->{    _id,    _type,    tagline,    columns,    address,    phone,    email,    copyrightText,    parentCompany,    parentCompanyUrl  }}
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  phone?: string
  email?: string
  address?: string
  announcementBar?: AnnouncementBar
  navigation?: Array<{
    label: string
    url: string
    _key: string
  }>
  footer: {
    _id: string
    _type: 'footer'
    tagline: string | null
    columns: Array<{
      title: string
      links?: Array<{
        label: string
        url: string
        _key: string
      }>
      _key: string
    }> | null
    address: string | null
    phone: string | null
    email: string | null
    copyrightText: string | null
    parentCompany: string | null
    parentCompanyUrl: string | null
  } | null
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == 'page' && slug.current == 'home'][0]{    _id,    _type,    name,    slug,      "pageBuilder": pageBuilder[]{    ...,    _type == "heroSection" => {      ...,      heroImage {        ...,        asset->      }    },    _type == "statsIconBar" => {      ...,      items[]{        ...,        icon {          ...,          asset->        }      }    },    _type == "featureBlock" => {      ...,      image {        ...,        asset->      }    },    _type == "comparisonTable" => {      ...,      checkIcon {        ...,        asset->      },      xIcon {        ...,        asset->      }    },    _type == "testimonialsCarousel" => {      ...,      icon {        ...,        asset->      }    },    _type == "imageCta" => {      ...,      backgroundImage {        ...,        asset->      }    },  },  }
export type HomepageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  pageBuilder: Array<
    | {
        _key: string
        _type: 'comparisonTable'
        headline: string
        subheadline?: string
        competitors?: Array<string>
        highlightColumnName?: string
        checkIcon: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        xIcon: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        rows?: Array<{
          feature: string
          values?: Array<boolean>
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'featureBlock'
        image: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        imagePosition?: 'left' | 'right'
        headline: string
        ctaText?: string
        ctaUrl?: string
        ctaVariant?: 'outline' | 'primary' | 'secondary'
        label?: string
        listItems?: Array<{
          icon?: string
          text: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'heroSection'
        ratingCount?: string
        headline: string
        headlineEmphasis?: string
        subtext?: string
        ctaText?: string
        ctaUrl?: string
        microCopy?: string
        heroImage: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
      }
    | {
        _key: string
        _type: 'imageCta'
        headline: string
        ctaText?: string
        ctaUrl?: string
        backgroundImage: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        overlayOpacity?: number
      }
    | {
        _key: string
        _type: 'statsBand'
        showLogo?: boolean
        stats?: Array<{
          value: string
          label: string
          icon?: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'statsIconBar'
        items: Array<{
          icon: {
            asset: {
              _id: string
              _type: 'sanity.imageAsset'
              _createdAt: string
              _updatedAt: string
              _rev: string
              originalFilename?: string
              label?: string
              title?: string
              description?: string
              altText?: string
              sha1hash?: string
              extension?: string
              mimeType?: string
              size?: number
              assetId?: string
              uploadId?: string
              path?: string
              url?: string
              metadata?: SanityImageMetadata
              source?: SanityAssetSourceData
            } | null
            media?: unknown // Unable to locate the referenced type "icon.media" in schema
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          } | null
          iconFallback?: string
          label: string
          _key: string
        }> | null
      }
    | {
        _key: string
        _type: 'testimonialsCarousel'
        icon: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        headline?: string
        testimonials?: Array<{
          quote: string
          name: string
          descriptor?: string
          _key: string
        }>
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,      "pageBuilder": pageBuilder[]{    ...,    _type == "heroSection" => {      ...,      heroImage {        ...,        asset->      }    },    _type == "statsIconBar" => {      ...,      items[]{        ...,        icon {          ...,          asset->        }      }    },    _type == "featureBlock" => {      ...,      image {        ...,        asset->      }    },    _type == "comparisonTable" => {      ...,      checkIcon {        ...,        asset->      },      xIcon {        ...,        asset->      }    },    _type == "testimonialsCarousel" => {      ...,      icon {        ...,        asset->      }    },    _type == "imageCta" => {      ...,      backgroundImage {        ...,        asset->      }    },  },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string | null
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'comparisonTable'
        headline: string
        subheadline?: string
        competitors?: Array<string>
        highlightColumnName?: string
        checkIcon: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        xIcon: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        rows?: Array<{
          feature: string
          values?: Array<boolean>
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'featureBlock'
        image: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        imagePosition?: 'left' | 'right'
        headline: string
        ctaText?: string
        ctaUrl?: string
        ctaVariant?: 'outline' | 'primary' | 'secondary'
        label?: string
        listItems?: Array<{
          icon?: string
          text: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'heroSection'
        ratingCount?: string
        headline: string
        headlineEmphasis?: string
        subtext?: string
        ctaText?: string
        ctaUrl?: string
        microCopy?: string
        heroImage: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
      }
    | {
        _key: string
        _type: 'imageCta'
        headline: string
        ctaText?: string
        ctaUrl?: string
        backgroundImage: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        overlayOpacity?: number
      }
    | {
        _key: string
        _type: 'statsBand'
        showLogo?: boolean
        stats?: Array<{
          value: string
          label: string
          icon?: string
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'statsIconBar'
        items: Array<{
          icon: {
            asset: {
              _id: string
              _type: 'sanity.imageAsset'
              _createdAt: string
              _updatedAt: string
              _rev: string
              originalFilename?: string
              label?: string
              title?: string
              description?: string
              altText?: string
              sha1hash?: string
              extension?: string
              mimeType?: string
              size?: number
              assetId?: string
              uploadId?: string
              path?: string
              url?: string
              metadata?: SanityImageMetadata
              source?: SanityAssetSourceData
            } | null
            media?: unknown // Unable to locate the referenced type "icon.media" in schema
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          } | null
          iconFallback?: string
          label: string
          _key: string
        }> | null
      }
    | {
        _key: string
        _type: 'testimonialsCarousel'
        icon: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        headline?: string
        testimonials?: Array<{
          quote: string
          name: string
          descriptor?: string
          _key: string
        }>
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<{
  slug: string
  _type: 'page'
  _updatedAt: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]{\n  ...,\n  footer->{\n    _id,\n    _type,\n    tagline,\n    columns,\n    address,\n    phone,\n    email,\n    copyrightText,\n    parentCompany,\n    parentCompanyUrl\n  }\n}': SettingsQueryResult
    '\n  *[_type == \'page\' && slug.current == \'home\'][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    \n  "pageBuilder": pageBuilder[]{\n    ...,\n    _type == "heroSection" => {\n      ...,\n      heroImage {\n        ...,\n        asset->\n      }\n    },\n    _type == "statsIconBar" => {\n      ...,\n      items[]{\n        ...,\n        icon {\n          ...,\n          asset->\n        }\n      }\n    },\n    _type == "featureBlock" => {\n      ...,\n      image {\n        ...,\n        asset->\n      }\n    },\n    _type == "comparisonTable" => {\n      ...,\n      checkIcon {\n        ...,\n        asset->\n      },\n      xIcon {\n        ...,\n        asset->\n      }\n    },\n    _type == "testimonialsCarousel" => {\n      ...,\n      icon {\n        ...,\n        asset->\n      }\n    },\n    _type == "imageCta" => {\n      ...,\n      backgroundImage {\n        ...,\n        asset->\n      }\n    },\n  }\n,\n  }\n': HomepageQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    \n  "pageBuilder": pageBuilder[]{\n    ...,\n    _type == "heroSection" => {\n      ...,\n      heroImage {\n        ...,\n        asset->\n      }\n    },\n    _type == "statsIconBar" => {\n      ...,\n      items[]{\n        ...,\n        icon {\n          ...,\n          asset->\n        }\n      }\n    },\n    _type == "featureBlock" => {\n      ...,\n      image {\n        ...,\n        asset->\n      }\n    },\n    _type == "comparisonTable" => {\n      ...,\n      checkIcon {\n        ...,\n        asset->\n      },\n      xIcon {\n        ...,\n        asset->\n      }\n    },\n    _type == "testimonialsCarousel" => {\n      ...,\n      icon {\n        ...,\n        asset->\n      }\n    },\n    _type == "imageCta" => {\n      ...,\n      backgroundImage {\n        ...,\n        asset->\n      }\n    },\n  }\n,\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
  }
}
